[package]
name = "inferis"
version = "0.1.0"
edition = "2021"
default-run = "inferis"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { path = "../engine" }
rand = "0.8.4"
lazy_static = "1.4.0"
